"""Change last new tables for columns in User table

Revision ID: b5a2a62f1ed6
Revises: b291e6392923
Create Date: 2026-01-21 18:10:24.390283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a2a62f1ed6'
down_revision: Union[str, Sequence[str], None] = 'b291e6392923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero eliminamos los índices y la tabla "hija" (la que tiene las foreign keys)
    op.drop_index(op.f('ix_user_attributes_id'), table_name='user_attributes')
    op.drop_table('user_attributes')
    
    # Después ya podemos eliminar la tabla "padre"
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_table('attributes')
    
    op.add_column('users', sa.Column('strength', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('stamina', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('intelligence', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('charisma', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'charisma')
    op.drop_column('users', 'intelligence')
    op.drop_column('users', 'stamina')
    op.drop_column('users', 'strength')
    
    # Primero creamos la tabla "padre"
    op.create_table('attributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('attributes_pkey')),
    sa.UniqueConstraint('name', name=op.f('attributes_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)

    # Después ya podemos crear la tabla "hija"
    op.create_table('user_attributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('user_attributes_attribute_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_attributes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_attributes_pkey'))
    )
    op.create_index(op.f('ix_user_attributes_id'), 'user_attributes', ['id'], unique=False)
    # ### end Alembic commands ###
